version: '3.7'

services:
  report:
    image: harbor.thepostway.com/postway/v1/report/dev
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2"
          memory: 8G
        reservations:
          cpus: "0.1"
          memory: 256M
    environment:
      TZ: "Asia/Bangkok"
      FLASK_DEBUG: "1"
      MONGODB_URI: "mongodb://admin:zypy9mavyl6sdqnsn8kn@128.199.129.154:27017/postway_development?authSource=admin"
      MONGODB_DATABASE: "postway_development"
    ports:
      - "30003:80"
    volumes:
      - postwaydev_log:/srv/flask_app/logs
    networks:
      frontend:
        aliases:
        - report_dev
      backend:
        aliases:
        - report_dev
    healthcheck:
      test: curl http://localhost:80/healthz || exit 1
      interval: 60s
      retries: 5
      start_period: 15s
      timeout: 10s

volumes:
  postwaydev_log:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.240,nolock,soft,rw,nfsvers=4,async
      device: ":/mnt/nfs_data/logs"

networks:
  frontend:
    name: fe
    external: true
  backend:
    name: be
    external: true